# Data

As you now the data is one of the machine learning components, the data is considerd as the feul of this world.

For machine learning engineers the data is like the air to the living beings, there is a phrase said '**Bad Data in, Bad Result out!**'

Coming up with features is difficult, time-consuming, requires expert knowledge. "Applied machine learning" is basically feature engineering.

—Andrew Ng, Stanford University

# What is Data Pre-Processsing?

Data preprocessing is a process of preparing the raw data and making it suitable for a machine learning model. It is the first and crucial step while creating a machine learning model. Data preprocessing in Machine Learning refers to the technique of preparing (cleaning and organizing) the raw data to make it suitable for a building and training Machine Learning models.

# Why do we need Data Preprocessing?

A real-world data generally contains noises, missing values, and maybe in an unusable format which cannot be directly used for machine learning models.

When it comes to creating a Machine Learning model, data preprocessing is the first step marking the initiation of the process. Data preprocessing is required tasks for cleaning the data and making it suitable for a machine learning model which also increases the accuracy and efficiency of a machine learning model.

# Data Preprocessing Steps
- Data Gathering.
- Importing Libraries.
- Load datasets.
- Finding Missing Data.
- Encoding Categorical Data.
- Splitting dataset into training and test set.
- Feature scaling.

## Data Gathering
To create a machine learning model, the first thing we required is a dataset as a machine learning model completely works on data. The collected data for a particular problem in a proper format is known as the dataset. Dataset formats differ according to use cases. For instance, a business dataset will be entirely different from a medical dataset. While a business dataset will contain relevant industry and business data, a medical dataset will include healthcare-related data.

### Where To Find Data
Here are the best 20 source of Data:
- <a href='https://data.worldbank.org/'>World bank</a>
- <a href='https://www.who.int/gho/database/en/'>World health organization</a>
- <a href='https://www.google.com/publicdata/directory'> Google data set</a>
- <a href='https://registry.opendata.aws/'> registry open data AWS</a>
- <a href='http://data.europa.eu/euodp/en/data/'>Europe open data</a>
- <a href='https://wiki.dbpedia.org/'>wiki dbpedia</a>
- <a href='https://www.yelp.com/dataset'>yelp</a>
- <a href='https://data.unicef.org/'>UNICEF</a>
- <a href='https://www.kaggle.com/datasets'>kaggle</a>
- <a href='https://archive.ics.uci.edu/ml/index.php'>machine learning repositary</a>
- <a href='https://www.data.gov/'>US data</a>
- <a href='https://www.census.gov/data.html'>US Census</a>
- <a href='https://healthdata.gov/search/type/dataset'>health data</a>
- <a href='https://data.gov.uk/'>data gov</a>
- <a href='https://data.gov.sa/ar/home'>open data</a>
- <a href='https://datasource.kapsarc.org/pages/home/'> kapsac</a>
- <a href='http://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42'>International monetary fund</a>
- <a href='https://www.visualdata.io/'>Visual data</a>
- <a href='http://insideairbnb.com/get-the-data.html'>Inside airbnb</a>
- <a href='https://ieee-dataport.org/'>IEEE</a>

You can also create a dataset by collecting data via different Python APIs. Once the dataset is ready, you must put it in a CSV, or HTML, or XLSX file formats.

## Importing Libraries
Since Python is the most extensively used and also the most preferred library by Data Scientists around the world, you must know how to import the python libraries for data analysis and data data visualization as you learn before.

Python libraries for data cleaning:
- Numpy
- Pandas
- Matplotlib
- seaborn

In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Load Dataset
After Gatharing The Data needed to your model you have to load it into your project, but before this step, we need to set the current directory as a working directory. in other words, the working file and the dataset file must be in the same directory(Folder)

In [44]:
data_set = pd.read_csv('Dataset.csv')

In [45]:
data_set

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Extract Independent and Dependent Variabels:

In [46]:
# xtracting independent variable:
x= data_set.iloc[:,:-1].values  

In [47]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [48]:
# Extracting dependent variable:
y= data_set.iloc[:,3].values  

In [49]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Finding Missing Data

if our dataset contains some missing data, then it may create a huge problem for our machine learning model. Hence it is necessary to handle missing values present in the dataset.
 so it is so important to identify and correctly handle the missing values, failing to do this, you might draw inaccurate and faulty conclusions and inferences from the data.

### Ways to handle missing Data:
- delete the particular row: The first way is used to commonly deal with null values. In this way,you remove a specific row that has a null value for a feature or a particular column where more than 75% of the values are missing. But this way is not so efficient and removing data may lead to loss of information which will not give the accurate output.

- calculate the mean: In this way, we will calculate the mean of that column or row which contains any missing value and will put it on the place of missing value. This strategy is useful for the features which have numeric data such as age, salary, year, etc. Here, we will use this approach.

we will use Scikit-learn library to handel missing values

In [50]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [51]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding Categorical Data
Categorical data refers to the information that has specific categories within the dataset. In the dataset cited above, there are two categorical variables – country and purchased.

categorical data is almost inevitable.Categorical variables represent types of data which may be divided into groups. Examples of categorical variables are race, sex, age group, educational level etc.

machine learning models are working on mathematics and numbers, and these variables are ofetn has letters or words. so you need to code these variables to be understood by the model.

In [52]:
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [53]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [54]:
# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [55]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the Dataset into Training and Testing sets
machine learning models require some data to be traind on it, these data called the training set. the model can train on that set of data to understand the realations between features and can predict new observations.

so we devid our dataset int two substs:

- **Training Set**: to train the machine learning model, and we already know the output.

- **Test set**: to test the machine learning model, and by using the test set, model predicts the output.



In [56]:
# Splitting data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

- **test_size**: the desired size of the test_set. 0.2 denotes 20%.
- **random_state**:  This is used to preserve the uniqueness. The split will happen uniquely for a random_state.

In [57]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [58]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [59]:
print(y_train)

[0 1 0 0 1 1 0 1]


## Feature scaling
The last step of data pre-processing ia feature scaling, It is a technique to standardize the independent variables of the dataset in a specific range. Scaling ensures that all data in a dataset falls in the same range.Unscaled data can cause inaccurate or false predictions.

In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [61]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [62]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
